base_url = "https://ostensible.info"
title = "Docs"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
logo = "https://i.ibb.co/r4B2211/ostensible-info.png"
release = "https://api.github.com/repos/getzola/zola/releases/latest"
favicon = "https://i.ibb.co/r4B2211/ostensible-info.png"
